### ISSUE TITLE
TypeError: Cannot read property 'device' of undefined

### ISSUE THREAD

**Issue by nicolazilio** [joaomgcd/JoinDesktop#5]
Sometimes I get this error message. However, it does not affect the functionality of the app

Unexpected Error: Cannot read property 'device' of undefined
```
Trace:
TypeError: Cannot read property 'device' of undefined
at AppHelperMedia.updateMediaInfo (file:///C:/Users/nicol/AppData/Local/com/app-0.1.0/resources/app.asar/v2/media/apphelpermedia.js:147:34)
at AppHelperMedia.onGCMRespondFile (file:///C:/Users/nicol/AppData/Local/com/app-0.1.0/resources/app.asar/v2/media/apphelpermedia.js:174:20)
at async EventBus.sendToRegistered (file:///C:/Users/nicol/AppData/Local/com/app-0.1.0/resources/app.asar/v2/eventbus.js:80:5)
at async EventBus.post (file:///C:/Users/nicol/AppData/Local/com/app-0.1.0/resources/app.asar/v2/eventbus.js:85:7)
at async Function.post (file:///C:/Users/nicol/AppData/Local/com/app-0.1.0/resources/app.asar/v2/eventbus.js:15:10)
```

**Comment by joaomgcd** [comment]
Ok, fixed for next release. Thank you! :)
