### ISSUE TITLE
Why is is installing in the WhatApp directory?

### ISSUE THREAD

**Issue by hrishikesh-deshpande** [joaomgcd/JoinDesktop#75]
This is the start of setup log

```2017-06-29 14:55:45> Program: Starting Squirrel Updater: --install .

2017-06-29 14:55:45> Program: Starting install, writing to C:\Users\Hrishikesh\AppData\Local\SquirrelTemp

2017-06-29 14:55:45> Program: About to install to: C:\Users\Hrishikesh\AppData\Local\WhatsApp

2017-06-29 14:55:46> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Hrishikesh\AppData\Local\WhatsApp\packages\RELEASES'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)

   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)

   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()

**Comment by joaomgcd** [comment]
Hi. When exactly are you getting that? Can you please clarify? Thanks

**Comment by tommyent** [comment]
I thought squirrel was EOL?

**Comment by hrishikesh-deshpande** [comment]
I downloaded the exe and launched it from the downloads folder by double clicking it. I had whatsapp desktop app open at the time.

**Comment by hrishikesh-deshpande** [comment]
@joaomgcd were you able to reproduce the bug?

**Comment by RuiNtD** [comment]
Squirrel uses the same file for all installer logs. That log is from when you actually installed WhatsApp.
